[tool.yapf]
column_limit = 100
dedent_closing_brackets = true
ignore_patterns = [
    "wykoj/test_cases/**/*.py"
]

[tool.isort]
line_length = 100
multi_line_output = 5
balanced_wrapping = true
skip_glob = [
    "wykoj/test_cases/*"
]

[tool.aerich]
tortoise_orm = "wykoj.tortoise_config.TORTOISE_CONFIG"
location = "./migrations"
src_folder = "./."
