[tool.yapf]
column_limit = 100
dedent_closing_brackets = true

[tool.isort]
line_length = 100
multi_line_output = 5
balanced_wrapping = true

[tool.aerich]
tortoise_orm = "wykoj.tortoise_config.TORTOISE_CONFIG"
location = "./migrations"
src_folder = "./."
